import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './main.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gray-100 text-gray-700 mx-auto my-16 max-w-[692px] px-6'>{children}</body>
    </html>
  )
}
